In [1]:
import pandas as pd
import numpy as np
import pickle

# Survey

In [3]:
# Loading DFs
with open ('./Clean Data R00/SURVEY_DF_age_bmi.pickle', 'rb') as handle:
    r00_survey = pickle.load(handle)
with open ('./Clean_DND/SURVEY_DND.pickle', 'rb') as handle:
    dnd_survey = pickle.load(handle)

In [4]:
# Check that the keys match
[i for i in r00_survey.keys()] == [i for i in dnd_survey.keys()]

True

In [5]:
cols = [i for i in r00_survey.keys()]
cols

['Demographics',
 'Medical Screening',
 'AVI',
 'BISBAS',
 'BIS',
 'TPQ-NS',
 'NEO-SF',
 'SWLS',
 'FTP',
 'SBQ']

In [7]:
#Add experiment column to all dataset
for col in cols:
    r00_survey[col]['Experiment'] = 'R00'

for col in cols:
    dnd_survey[col]['Experiment'] = 'DND'

---

In [9]:
#Check for every table that they have the same column name
set.difference(set(r00_survey[cols[0]].columns), set(dnd_survey[cols[0]].columns))

{'Lives_with', 'Marital_Status', 'Religion'}

In [10]:
#DND does not have lives with nor religion.
#Lets rename Marital_status
dnd_survey[cols[0]].rename(columns = {'Marital_status' : 'Marital_Status'}, inplace = True)

In [134]:
set(dnd_survey['Demographics'].columns) - set.intersection(set(r00_survey['Demographics'].columns), set(dnd_survey['Demographics'].columns))

{'Race'}

In [136]:
set.intersection(set(r00_survey['Demographics'].columns), set(dnd_survey['Demographics'].columns))

{'Age',
 'Children',
 'Education',
 'Ethnicity',
 'Experiment',
 'Household_income',
 'Marital_Status',
 'Medications',
 'Occupation',
 'Sex',
 'Subject'}

In [11]:
DEMOGRAPHICS = pd.concat( [r00_survey['Demographics'] , dnd_survey['Demographics']], sort= False)

In [12]:
DEMOGRAPHICS

,Subject,Occupation,Education,Ethnicity,Religion,Sex,Marital_Status,Children,Lives_with,Household_income,Medications,Age,Experiment,Race
0,1002,Restaurant worker,14,White,Buddhism,Female,Single,0.0,"Mother, father, two younger brothers","$10,000-$19,999",None,32.0,R00,NaN
1,1004,Student/Coach,14,White/Pacific Islander,Questionable,Male,Single,0.0,Grandparents,"$10,000-$19,999",None,28.0,R00,NaN
2,1008,IT Manager,16,White,Judiasm,Male,Married,2.0,"Wife, two children","$150,000 or more",Aciphex,46.0,R00,NaN
3,1009,Professor,22,White,Judiasm,Male,Married,0.0,Spouse/partner,"$150,000 or more",None,58.0,R00,NaN
4,1014,Realtor,18,White,Christianity,Female,Married,3.0,Spouse/partner,"$120,000-$129,999","Lipitor, Diovan, 81mg Aspirin",68.0,R00,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
117,DND118,Artist,"BA from Stanford, JD from Univ of Michigan",White,NaN,Male,Married,1.0,NaN,"$150,000 or more",NaN,59.0,DND,5.0
118,DND119,Associate FedEx,"College, Masters",Black,NaN,Male,Divorced,1.0,NaN,"$90,000-$99,999",NaN,57.0,DND,4.0
119,DND120,Finisher,12th,White,NaN,Male,Single,2.0,NaN,"$30,000-$39,999",NaN,50.0,DND,5.0
120,DND121,Valet Parking & Rideshare Driver,"High School Diploma, BA, MBA",White,NaN,Male,Married,4.0,NaN,"$70,000-$79,999",NaN,61.0,DND,5.0
121,DND122,Mailhandler,Bachelor of Science Degree,Black,NaN,Male,Married,3.0,NaN,"$120,000-$129,999",NaN,50.0,DND,4.0

---

In [137]:
set.intersection(set(r00_survey['Medical Screening'].columns), set(dnd_survey['Medical Screening'].columns))

{'BMI', 'Experiment', 'Height (cm)', 'Subject', 'Weight (kg)'}

In [13]:
MEDICAL_SCREENING = pd.concat( [r00_survey['Medical Screening'] , dnd_survey['Medical Screening']], sort= False)
MEDICAL_SCREENING

,Subject,Med History,Height (cm),Weight (kg),Vitals: Temp (˚F),Vitals: Pulse,Vitals: Resp/min,Vitals: BP,Allergies:,Physical: General Appearance,...,Toxicology: Opiates,Toxicology: Oxycodone,Toxicology: Phencyclidine,Toxicology: Methadone,MRI Eligibility?,PET Eligbility?,Notes/Specific Abnormalities:,BMI,Age,Experiment
0,1002,Psychiatric disorder-P. Grandmother,161.000000,61.5,98.0,73.0,16.0,117/84,Penicillin,Normal,...,Negative,Negative,Negative,Negative,Yes,Yes,NaN,23.725936,32.0,R00
1,1004,Paxil-2014 (2 month usage),174.000000,91.5,97.9,50.0,20.0,132/73,None,Normal,...,Negative,Negative,Negative,Negative,Yes,Yes,NaN,30.221958,28.0,R00
2,1008,"Current: EPAP apnea, RX-20mg acifex, 1995- her...",182.000000,103.7,97.2,77.0,16.0,118/72,None,Normal,...,Negative,Negative,Negative,Negative,Yes,Yes,NaN,31.306605,46.0,R00
3,1009,None,175.000000,87.0,96.7,54.0,16.0,118/70,None,Normal,...,Negative,Negative,Negative,Negative,Yes,Yes,NaN,28.408163,58.0,R00
4,1014,"HBP, high cholesterol, daughter-MDD, father-MI...",167.600000,87.8,98.4,100.0,16.0,111/80,None,Normal,...,Negative,Negative,Negative,Negative,Yes,Yes,NaN,31.256942,68.0,R00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
117,DND118,NaN,177.930854,72.5,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22.900000,NaN,DND
118,DND119,NaN,175.370228,97.8,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,31.800000,NaN,DND
119,DND120,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,DND
120,DND121,NaN,182.894211,114.4,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,34.200000,NaN,DND
121,DND122,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,DND

---

In [14]:
AVI = pd.concat( [r00_survey['AVI'] , dnd_survey['AVI']], sort= False)

In [15]:
set(dnd_survey['AVI'].columns) - set.intersection(set(r00_survey['AVI'].columns), set(dnd_survey['AVI'].columns))
#all the DND cols are in the concatenate version

set()

In [138]:
set.intersection(set(r00_survey['AVI'].columns), set(dnd_survey['AVI'].columns))

{'Experiment',
 'HAN_actual',
 'HAN_ideal',
 'HAP_actual',
 'HAP_ideal',
 'HA_actual',
 'HA_ideal',
 'LAN_actual',
 'LAN_ideal',
 'LAP_actual',
 'LAP_ideal',
 'LA_actual',
 'LA_ideal',
 'N_actual',
 'N_ideal',
 'P_actual',
 'P_ideal',
 'Subject'}

In [16]:
AVI

,index,Subject,Actually Feel: Enthusiastic,Actual HAP,Actually Feel: Dull,Actual LAN,Actually Feel: Excited,Actual HAP.1,Actually Feel: Sleepy,Actual LAN.1,...,HA_actual,HAP_ideal,P_ideal,LAP_ideal,LA_ideal,LAN_ideal,N_ideal,HAN_ideal,HA_ideal,Experiment
1,1.0,1002,H,3.0,A,2.0,M,4.0,A,2.0,...,2.000000,4.0,5.000000,4.8,2.0,1.0,1.000000,1.000000,3.333333,R00
3,3.0,1004,H,3.0,A,2.0,M,4.0,H,3.0,...,2.666667,4.4,4.333333,4.0,2.2,2.0,1.333333,1.666667,3.333333,R00
7,7.0,1008,H,3.0,A,2.0,H,3.0,A,2.0,...,2.000000,3.2,5.000000,4.0,2.0,1.0,1.000000,1.000000,2.000000,R00
8,8.0,1009,M,4.0,A,2.0,M,4.0,A,2.0,...,2.333333,3.8,3.666667,3.4,2.4,2.0,2.000000,1.666667,2.666667,R00
13,13.0,1014,M,4.0,N,1.0,H,3.0,A,2.0,...,2.333333,3.8,4.000000,4.2,1.4,1.0,1.000000,1.333333,2.333333,R00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
117,NaN,DND118,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,7.000000,17.0,12.000000,16.0,5.0,3.0,3.000000,3.000000,8.000000,DND
118,NaN,DND119,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,8.000000,15.0,12.000000,18.0,7.0,5.0,4.000000,3.000000,10.000000,DND
119,NaN,DND120,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,DND
120,NaN,DND121,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,7.000000,18.0,15.000000,24.0,9.0,4.0,3.000000,3.000000,9.000000,DND
121,NaN,DND122,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,DND

---

In [17]:
set(dnd_survey['BISBAS'].columns) - set.intersection(set(r00_survey['BISBAS'].columns), set(dnd_survey['BISBAS'].columns))

set()

In [18]:
set.intersection(set(r00_survey['BISBAS'].columns), set(dnd_survey['BISBAS'].columns))

{'BAS_D', 'BAS_FS', 'BAS_RR', 'BIS.5', 'Experiment', 'Subject'}

In [19]:
BISBAS = pd.concat( [r00_survey['BISBAS'] , dnd_survey['BISBAS']], sort= False)
BISBAS

,index,Subject,"1) When I get something I want, I feel excited and energized.",BAS RR,"2) If I think something unpleasant is about to happen, I usually get pretty worked up.",BIS,"3) If I see a chance to get something I want, I move in on it right away.",BAS Drive,4) I worry about making mistakes.,BIS.1,...,BIS-reverse.1,"19)When good things happen to me, it affects me strongly.",BAS RR.3,"20) When I see an opportunity for something I like, I get excited right away.",BAS RR.4,BIS.5,BAS_D,BAS_FS,BAS_RR,Experiment
1,1.0,1002,5.0,5.0,4.0,4.0,4.0,4.0,3.0,3.0,...,3.0,5.0,5.0,5.0,5.0,21.0,15.0,16.0,24.0,R00
3,3.0,1004,5.0,5.0,3.0,3.0,4.0,4.0,1.0,1.0,...,3.0,5.0,5.0,5.0,5.0,22.0,14.0,18.0,25.0,R00
7,7.0,1008,5.0,5.0,4.0,4.0,3.0,3.0,4.0,4.0,...,3.0,4.0,4.0,3.0,3.0,27.0,11.0,12.0,21.0,R00
8,8.0,1009,4.0,4.0,3.0,3.0,4.0,4.0,3.0,3.0,...,3.0,3.0,3.0,4.0,4.0,21.0,13.0,12.0,19.0,R00
13,13.0,1014,5.0,5.0,2.0,2.0,4.0,4.0,2.0,2.0,...,3.0,3.0,3.0,4.0,4.0,19.0,14.0,11.0,18.0,R00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
117,NaN,DND118,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,20.0,10.0,14.0,15.0,DND
118,NaN,DND119,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,17.0,7.0,9.0,10.0,DND
119,NaN,DND120,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,DND
120,NaN,DND121,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,20.0,10.0,12.0,14.0,DND
121,NaN,DND122,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,DND

---

In [20]:
#BIS
set(dnd_survey['BIS'].columns) - set.intersection(set(r00_survey['BIS'].columns), set(dnd_survey['BIS'].columns))

set()

In [21]:
set.intersection(set(r00_survey['BIS'].columns), set(dnd_survey['BIS'].columns))

{'BIS_total', 'Experiment', 'Subject'}

In [22]:
BIS =  pd.concat( [r00_survey['BIS'] , dnd_survey['BIS']], sort= False)
BIS

,index,Subject,1) I plan tasks carefully.,Self Control/Nonplanning-reverse,2) I do things without thinking.,3) I make up my mind quickly.,4) I am happy-go-lucky.,"5) I don't ""pay attention"".","6) I have ""racing"" thoughts.",7) I plan trips well ahead of time.,...,Attention_1,CogIns,Motor_1,Perserverance,Self-Control,CogComp,Attention_2,Motor_2,Nonplanning,Experiment
1,1.0,1002,3.0,2.0,2.0,3.0,3.0,1.0,3.0,4.0,...,8.0,6.0,15.0,8.0,9.0,9.0,14.0,23.0,18.0,R00
3,3.0,1004,3.0,2.0,2.0,3.0,4.0,2.0,2.0,4.0,...,10.0,7.0,19.0,9.0,10.0,12.0,17.0,28.0,22.0,R00
7,7.0,1008,3.0,2.0,1.0,2.0,2.0,2.0,3.0,2.0,...,11.0,7.0,12.0,7.0,13.0,12.0,18.0,19.0,25.0,R00
8,8.0,1009,4.0,1.0,2.0,3.0,3.0,1.0,1.0,3.0,...,7.0,3.0,12.0,6.0,9.0,8.0,10.0,18.0,17.0,R00
13,13.0,1014,3.0,2.0,1.0,3.0,2.0,3.0,2.0,4.0,...,9.0,6.0,12.0,7.0,10.0,8.0,15.0,19.0,18.0,R00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
117,NaN,DND118,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,DND
118,NaN,DND119,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,DND
119,NaN,DND120,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,DND
120,NaN,DND121,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,DND
121,NaN,DND122,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,DND

In [23]:
BIS.drop(columns='index',inplace= True)

---

In [24]:
#TPQ-NS
set(dnd_survey['TPQ-NS'].columns) - set.intersection(set(r00_survey['TPQ-NS'].columns), set(dnd_survey['TPQ-NS'].columns))

set()

In [25]:
 set.intersection(set(r00_survey['TPQ-NS'].columns), set(dnd_survey['TPQ-NS'].columns))

{'Experiment', 'NS_total', 'Subject'}

In [27]:
TPQ_NS =  pd.concat( [r00_survey['TPQ-NS'] , dnd_survey['TPQ-NS']], sort= False)

In [28]:
TPQ_NS

,Subject,"1) I often try new things just for fun or thrills, even if most people think it's a waste of time.",NS1,"2) When nothing new is happening, I usually start looking for something thrilling or exciting.",NS1.1,3) I usually demand very good practical reasons before I'm willing to change my old ways of doing things.,NS1.2,"4) I hate to change the way I do things, even if many people tell me there is a new and better way to do it.",NS1.3,5) I like it when people can do whatever they want without strict rules and regulations.,...,33) I like to stay at home better than to travel or explore new places.,NS1.8,34) I like to pay close attention to details in everything I do.,NS2.7,NS1.9,NS2.8,NS3.7,NS4.10,NS_total,Experiment
1,1002,T,1.0,T,1.0,T,0.0,T,0.0,T,...,F,1.0,T,0.0,5.0,2.0,2.0,7.0,16.0,R00
3,1004,T,1.0,T,1.0,T,0.0,F,1.0,T,...,F,1.0,T,0.0,7.0,2.0,5.0,4.0,18.0,R00
7,1008,F,0.0,T,1.0,T,0.0,T,0.0,F,...,F,1.0,T,0.0,5.0,2.0,3.0,1.0,11.0,R00
8,1009,F,0.0,T,1.0,T,0.0,F,1.0,T,...,F,1.0,T,0.0,4.0,0.0,1.0,2.0,7.0,R00
13,1014,F,0.0,F,0.0,T,0.0,T,0.0,F,...,F,1.0,T,0.0,2.0,2.0,3.0,2.0,9.0,R00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
117,DND118,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17.0,DND
118,DND119,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18.0,DND
119,DND120,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,DND
120,DND121,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16.0,DND
121,DND122,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,DND

---

In [29]:
#NEO-SF

In [30]:
set(dnd_survey['NEO-SF'].columns) - set.intersection(set(r00_survey['NEO-SF'].columns), set(dnd_survey['NEO-SF'].columns))

set()

In [31]:
 set.intersection(set(r00_survey['NEO-SF'].columns), set(dnd_survey['NEO-SF'].columns))

{'Conscientiousness', 'Experiment', 'Extraversion', 'Neuroticism', 'Subject'}

In [32]:
NEO_SF =  pd.concat( [r00_survey['NEO-SF'] , dnd_survey['NEO-SF']], sort= False)

In [33]:
NEO_SF.drop(columns= 'index', inplace=True)

In [47]:
NEO_SF

,Subject,1) I am not a worrier.,N-r,2) I like to have a lot of people around me.,E,3) I don't like to waste my time daydreaming.,O-r,4) I try to be courteous to everyone I meet.,A,5) I keep my belongings clean and neat.,...,"59) If necessary, I am willing to manipulate people to get what I want.",A-r.7,60) I strive for excellence in everything I do.,C.7,Neuroticism,Extraversion,Openness,Agreeableness,Conscientiousness,Experiment
1,1002,Agree,2.0,Disagree,2.0,Disagree,4.0,Strongly Agree,5.0,Agree,...,Disagree,4.0,Agree,4.0,26.0,48.0,47.0,48.0,46.0,R00
3,1004,Agree,2.0,Agree,4.0,Strongly Disagree,5.0,Strongly Agree,5.0,Agree,...,Disagree,4.0,Strongly Agree,5.0,28.0,48.0,46.0,49.0,49.0,R00
7,1008,Disagree,4.0,Agree,4.0,Neutral,3.0,Strongly Agree,5.0,Agree,...,Disagree,4.0,Agree,4.0,28.0,47.0,28.0,50.0,48.0,R00
8,1009,Disagree,4.0,Neutral,3.0,Disagree,4.0,Agree,4.0,Agree,...,Disagree,4.0,Agree,4.0,26.0,45.0,42.0,43.0,48.0,R00
13,1014,Neutral,3.0,Disagree,2.0,Disagree,4.0,Strongly Agree,5.0,Strongly Agree,...,Disagree,4.0,Agree,4.0,26.0,36.0,41.0,42.0,49.0,R00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
117,DND118,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,137.0,166.0,NaN,NaN,142.0,DND
118,DND119,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,86.0,148.0,NaN,NaN,168.0,DND
119,DND120,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,DND
120,DND121,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,117.0,159.0,NaN,NaN,163.0,DND
121,DND122,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,DND

We have a problem. The experiments used a different instrument to measure the personality.
Researching about this I realized that the minimum and maximum values for every dimesion is different depending on the test used.

                (min, max)

`R00 -> FFI ->  (12, 60)`

`DND -> PIR3 -> (48, 240)`

We could scale it using:

$$\dfrac{x_i - min(x)}{max(x) - min(x)}$$

In [50]:
cols_to_modif = ['Neuroticism', 'Extraversion', 'Conscientiousness']
new_cols = ['Neuroticism_scaled', 'Extraversion_scaled', 'Conscientiousness_scaled']

def min_max(x, minimum, maximum):
    '''https://en.wikipedia.org/wiki/Feature_scaling'''
    return (x - minimum) / (maximum - minimum)

In [91]:
#This is not maybe the ideal option but it gives similar values
min_max(dnd_survey['NEO-SF']['Conscientiousness'], minimum = 48, maximum = 240).mean() , min_max( r00_survey['NEO-SF']['Conscientiousness'], minimum = 12, maximum = 60).mean()

(0.6627083333333335, 0.7453703703703703)

In [90]:
min_max(dnd_survey['NEO-SF']['Neuroticism'], minimum = 48, maximum = 240).mean() , min_max(r00_survey['NEO-SF']['Neuroticism'], minimum = 12, maximum = 60).mean()

(0.34159722222222216, 0.2922453703703704)

In [92]:
min_max(dnd_survey['NEO-SF']['Extraversion'], minimum = 48, maximum = 240).mean() , min_max( r00_survey['NEO-SF']['Extraversion'], minimum = 12, maximum = 60).mean()

(0.5715277777777779, 0.5850694444444445)

In [95]:
#R00
for col,new_col in zip(cols_to_modif,new_cols):
    r00_survey['NEO-SF'][new_col] =  min_max(r00_survey['NEO-SF'][col], minimum = 12, maximum = 60)

In [102]:
#DND
for col,new_col in zip(cols_to_modif,new_cols):
    dnd_survey['NEO-SF'][new_col] =  min_max(dnd_survey['NEO-SF'][col], minimum = 48, maximum = 240)

In [103]:
NEO_SF =  pd.concat( [r00_survey['NEO-SF'] , dnd_survey['NEO-SF']], sort = False)

In [104]:
NEO_SF

,index,Subject,1) I am not a worrier.,N-r,2) I like to have a lot of people around me.,E,3) I don't like to waste my time daydreaming.,O-r,4) I try to be courteous to everyone I meet.,A,...,C.7,Neuroticism,Extraversion,Openness,Agreeableness,Conscientiousness,Experiment,Neuroticism_scaled,Extraversion_scaled,Conscientiousness_scaled
1,1.0,1002,Agree,2.0,Disagree,2.0,Disagree,4.0,Strongly Agree,5.0,...,4.0,26.0,48.0,47.0,48.0,46.0,R00,0.291667,0.750000,0.708333
3,3.0,1004,Agree,2.0,Agree,4.0,Strongly Disagree,5.0,Strongly Agree,5.0,...,5.0,28.0,48.0,46.0,49.0,49.0,R00,0.333333,0.750000,0.770833
7,7.0,1008,Disagree,4.0,Agree,4.0,Neutral,3.0,Strongly Agree,5.0,...,4.0,28.0,47.0,28.0,50.0,48.0,R00,0.333333,0.729167,0.750000
8,8.0,1009,Disagree,4.0,Neutral,3.0,Disagree,4.0,Agree,4.0,...,4.0,26.0,45.0,42.0,43.0,48.0,R00,0.291667,0.687500,0.750000
13,13.0,1014,Neutral,3.0,Disagree,2.0,Disagree,4.0,Strongly Agree,5.0,...,4.0,26.0,36.0,41.0,42.0,49.0,R00,0.291667,0.500000,0.770833
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
117,NaN,DND118,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,137.0,166.0,NaN,NaN,142.0,DND,0.463542,0.614583,0.489583
118,NaN,DND119,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,86.0,148.0,NaN,NaN,168.0,DND,0.197917,0.520833,0.625000
119,NaN,DND120,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,DND,NaN,NaN,NaN
120,NaN,DND121,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,117.0,159.0,NaN,NaN,163.0,DND,0.359375,0.578125,0.598958
121,NaN,DND122,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,DND,NaN,NaN,NaN

---

In [105]:
#SWLS

In [106]:
set(dnd_survey['SWLS'].columns) - set.intersection(set(r00_survey['SWLS'].columns), set(dnd_survey['SWLS'].columns))

set()

In [107]:
 set.intersection(set(r00_survey['SWLS'].columns), set(dnd_survey['SWLS'].columns))

{'Experiment', 'SWLS', 'Subject'}

In [108]:
SWLS =  pd.concat( [r00_survey['SWLS'] , dnd_survey['SWLS']], sort= False)

In [109]:
SWLS

,Subject,1) In most ways my life is close to ideal.,2) The conditions of my life are excellent.,3) I am satisfied with my life.,4) So far I have gotten the important things I want in life.,"5) If I could live my life over, I would change almost nothing.",SWLS,Experiment
1,1002,4.0,5.0,5.0,4.0,2.0,20.0,R00
3,1004,5.0,4.0,4.0,6.0,6.0,25.0,R00
7,1008,5.0,5.0,5.0,5.0,4.0,24.0,R00
8,1009,5.0,4.0,5.0,5.0,3.0,22.0,R00
13,1014,5.0,5.0,5.0,5.0,5.0,25.0,R00
...,...,...,...,...,...,...,...,...
117,DND118,NaN,NaN,NaN,NaN,NaN,19.0,DND
118,DND119,NaN,NaN,NaN,NaN,NaN,23.0,DND
119,DND120,NaN,NaN,NaN,NaN,NaN,NaN,DND
120,DND121,NaN,NaN,NaN,NaN,NaN,4.0,DND
121,DND122,NaN,NaN,NaN,NaN,NaN,NaN,DND

---

In [110]:
#FTP
set(dnd_survey['FTP'].columns) - set.intersection(set(r00_survey['FTP'].columns), set(dnd_survey['FTP'].columns))

set()

In [111]:
set.intersection(set(r00_survey['FTP'].columns), set(dnd_survey['FTP'].columns))

{'Experiment', 'FTP', 'Subject'}

In [112]:
FTP =  pd.concat( [r00_survey['FTP'] , dnd_survey['FTP']], sort= False)

In [113]:
FTP

,Subject,1) Many opportunities await me in the future.,2) I expect that I will set many new goals in the future.,3) My future is filled with possibilities.,4) Most of my life lies ahead of me.,5) My future seems infinite to me.,6) I could do anything I want in the future.,7) There is plenty of time left in my life to make new plans.,8) I have the sense that time is running out.,Revese,9) There are only limited possibilities in my future.,Reverse,"10) As I get older, I begin to experience time as limited.",Reverse.1,FTP,Experiment
1,1002,7.0,7.0,7.0,7.0,7.0,7.0,7.0,1.0,7.0,2.0,6.0,2.0,6.0,6.8,R00
3,1004,7.0,7.0,7.0,6.0,6.0,7.0,7.0,6.0,2.0,6.0,2.0,6.0,2.0,5.3,R00
7,1008,5.0,5.0,6.0,6.0,3.0,4.0,5.0,2.0,6.0,3.0,5.0,3.0,5.0,5.0,R00
8,1009,6.0,6.0,6.0,4.0,4.0,5.0,6.0,4.0,4.0,2.0,6.0,5.0,3.0,5.0,R00
13,1014,4.0,4.0,4.0,3.0,4.0,5.0,3.0,5.0,3.0,4.0,4.0,5.0,3.0,3.7,R00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
117,DND118,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,51.0,DND
118,DND119,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,54.0,DND
119,DND120,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,DND
120,DND121,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,35.0,DND
121,DND122,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,DND

---

In [114]:
#SBQ

In [115]:
set(dnd_survey['SBQ'].columns) - set.intersection(set(r00_survey['SBQ'].columns), set(dnd_survey['SBQ'].columns))

{'Q1',
 'Q10',
 'Q11',
 'Q12',
 'Q13',
 'Q14',
 'Q15',
 'Q16',
 'Q17',
 'Q18',
 'Q2',
 'Q3',
 'Q4',
 'Q5',
 'Q6',
 'Q7',
 'Q8',
 'Q9'}

In [122]:
r00_survey['SBQ'].columns = ['Subject', 'Q1', 'Q2', 'Q3', 'Q4', 'Q5', 'Q6', 'Q7', 'Q8',
       'Q9', 'Q10', 'Q11', 'Q12', 'Q13', 'Q14', 'Q15', 'Q16', 'Q17','Q18', 'SBQ', 'Experiment']
set(dnd_survey['SBQ'].columns) - set.intersection(set(r00_survey['SBQ'].columns), set(dnd_survey['SBQ'].columns))

set()

In [123]:
set.intersection(set(r00_survey['SBQ'].columns), set(dnd_survey['SBQ'].columns))

{'Experiment',
 'Q1',
 'Q10',
 'Q11',
 'Q12',
 'Q13',
 'Q14',
 'Q15',
 'Q16',
 'Q17',
 'Q18',
 'Q2',
 'Q3',
 'Q4',
 'Q5',
 'Q6',
 'Q7',
 'Q8',
 'Q9',
 'SBQ',
 'Subject'}

In [124]:
SBQ =  pd.concat( [r00_survey['SBQ'] , dnd_survey['SBQ']], sort = False)

In [125]:
SBQ

,Subject,Q1,Q2,Q3,Q4,Q5,Q6,Q7,Q8,Q9,...,Q11,Q12,Q13,Q14,Q15,Q16,Q17,Q18,SBQ,Experiment
1,1002,3.0,2.0,4.0,2.0,2.0,3.0,2.0,4.0,4.0,...,4.0,4.0,4.0,4.0,2.0,4.0,4.0,2.0,55.0,R00
3,1004,1.0,1.0,4.0,2.0,1.0,2.0,2.0,4.0,4.0,...,3.0,1.0,3.0,4.0,2.0,4.0,4.0,2.0,45.0,R00
7,1008,3.0,2.0,4.0,2.0,3.0,3.0,4.0,4.0,4.0,...,4.0,4.0,3.0,4.0,2.0,3.0,2.0,3.0,57.0,R00
8,1009,4.0,3.0,5.0,1.0,2.0,2.0,1.0,4.0,5.0,...,4.0,4.0,2.0,3.0,2.0,5.0,2.0,1.0,53.0,R00
13,1014,2.0,2.0,4.0,3.0,2.0,1.0,3.0,5.0,5.0,...,4.0,5.0,3.0,3.0,1.0,4.0,2.0,4.0,55.0,R00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
117,DND118,3.0,3.0,4.0,3.0,4.0,2.0,2.0,2.0,4.0,...,3.0,4.0,3.0,3.0,3.0,4.0,3.0,3.0,53.0,DND
118,DND119,3.0,3.0,4.0,2.0,4.0,2.0,2.0,4.0,4.0,...,3.0,4.0,4.0,3.0,2.0,4.0,1.0,4.0,52.0,DND
119,DND120,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,DND
120,DND121,2.0,3.0,4.0,2.0,2.0,4.0,2.0,4.0,4.0,...,4.0,4.0,2.0,4.0,4.0,4.0,4.0,2.0,55.0,DND
121,DND122,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,DND

----

Let's save all this tables in a dictionary

In [126]:
# Let's list all the different tables
tables = ['DEMOGRAPHICS','MEDICAL_SCREENING','AVI','BISBAS','BIS','TPQ_NS','NEO_SF','SWLS','FTP','SBQ']

In [129]:
SURVEY_DND_R00 = {}
#This loop assign a key and a table to the dict
for table in tables:
    SURVEY_DND_R00[table] = eval(table)

In [131]:
SURVEY_DND_R00.keys()

dict_keys(['DEMOGRAPHICS', 'MEDICAL_SCREENING', 'AVI', 'BISBAS', 'BIS', 'TPQ_NS', 'NEO_SF', 'SWLS', 'FTP', 'SBQ'])

In [133]:
with open('./All_clean_data/SURVEY_R00_DND.pickle', 'wb') as handle:
    pickle.dump(SURVEY_DND_R00,handle)

# What data we should use for our model?
Detailed by table:

- DEMOGRAPHICS
        {'Age',
         'Children',
         'Ethnicity',
         'Experiment',
         'Household_income',
         'Marital_Status',
         'Sex',
         'Subject'}
<br>
- MEDICAL SCREENING
        {'BMI',
        'Experiment',
        'Height (cm)',
        'Subject',
        'Weight (kg)}
<br>    
-  'AVI'
        {'Experiment',
         'HAN_actual', 'HAN_ideal', 
         'HAP_actual', 'HAP_ideal',
         'HA_actual', 'HA_ideal',
         'LAN_actual', 'LAN_ideal',
         'LAP_actual', 'LAP_ideal',
         'LA_actual', 'LA_ideal',
         'N_actual', 'N_ideal',
         'P_actual', 'P_ideal',
         'Subject'}
<br>
- 'BISBAS'
        {'BAS_D', 'BAS_FS', 'BAS_RR', 'BIS.5', 'Experiment', 'Subject'}
<br>    
- 'BIS'
        {'BIS_total', 'Experiment', 'Subject'}
<br>
- 'TPQ-NS'
        {'Experiment', 'NS_total', 'Subject'}
<br>    
- 'NEO-SF'
        {'Conscientiousness', 'Experiment', 'Extraversion', 'Neuroticism', 'Subject'}
<br>    
- 'SWLS'
        {'Experiment', 'SWLS', 'Subject'}
<br>    
- 'FTP'
        {'Experiment', 'FTP', 'Subject'}
<br>    
- 'SBQ'
        {'Experiment','SBQ','Subject'}

### CAUTION
The table demographic does not count with the variables `education` (this one could be recoded in some way if we need to), `religion` and `lives_with`